export const siteConfig = {
  academyName: "CHECK MATE School of Chess",
  tagline: "Beginners to Advance Level",
  contact: {
    phones: ["+91 96776 21073", "+91 88704 06066"],
    whatsapp: "919677621073", // For floating button
    email: "checkmatechess16@gmail.com",
    address: "80, Maniyam Vellpan Street,\nK.K. Pudur,\nCoimbatore – 641038",
  },
  social: {
    facebook: "#",
    instagram: "https://www.instagram.com/checkmateschoolofchess/",
    twitter: "#",
    youtube: "#",
  },
  integrations: {
    googlePhotosAlbumUrl: "#", // Add your Google Photos shared album URL here
    youtubeChannelUrl: "#", // Add your YouTube Channel URL here
    googleSheetsApiUrl: "#", // Add your Google Apps Script Web App URL here
    googleFormEmbedUrl: "https://docs.google.com/forms/d/e/1FAIpQLSeDKjYGB-Z3O6MD_jC_O-RIx2qSinEjY5bbQQBJR0OD5khj0Q/viewform?embedded=true", 
    classIssuesFormUrl: "https://docs.google.com/forms/d/e/1FAIpQLSeDKjYGB-Z3O6MD_jC_O-RIx2qSinEjY5bbQQBJR0OD5khj0Q/viewform?embedded=true", // Placeholder, change later
    googleBusinessReviewEmbed: "#", // URL or iframe for Google Reviews
  },
  seo: {
    defaultTitle: "CHECK MATE School of Chess | Beginners to Advance Level",
    defaultDescription: "Join CHECK MATE School of Chess in Coimbatore. We offer regular, weekend, and online chess classes for beginners to advanced players.",
    keywords: "chess academy, chess classes, coimbatore chess, online chess classes, learn chess, CHECK MATE school of chess, checkmatecbe, checkmate cbe",
    url: "https://checkmatecbe.com",
  },
  branches: [
    {
      id: "saibaba-colony",
      name: "Saibaba Colony Branch",
      address: "80, Maniyam Vellpan Street, K.K. Pudur, Coimbatore – 641038",
      googleMapsUrl: "https://maps.app.goo.gl/BV4Mr2mjaeSmEt627", 
      phone: "+91 96776 21073",
      timings: "Mon-Sat: 4:00 PM - 8:00 PM",
      image: "/images/saibabacolony.png"
    },
    {
      id: "peelamedu",
      name: "Peelamedu Branch",
      address: "24-42, Avarampalayam Road, Peelamedu, Coimbatore - 641004",
      googleMapsUrl: "https://maps.app.goo.gl/bpvsTyVkcAa7njaaA", 
      phone: "+91 88704 06066",
      timings: "Mon-Sat: 4:00 PM - 8:00 PM",
      image: "/images/peelamedu.jpg"
    }
  ],
  courses: [
    {
      id: "foundation",
      title: "Foundation",
      description: "Introduction to Chess fundamentals and building a strong foundation. We cover Board Basics, Pieces Movement, Basic Tactics, and Rules & Regulations.",
      duration: "3 Months",
      ageGroup: "5+ Years",
      fees: "Contact for details",
      chapters: [
        { title: "01 The Chessboard & Pieces", topics: ["How the chessboard is arranged", "How to recognize the 64 light and dark squares", "How to place the chessboard correctly", "How to name squares using files and ranks", "How to identify files, ranks, and diagonals", "How to recognize all six types of chess pieces", "How to arrange the pieces in their starting position", "How to understand the basic layout of the chessboard"] },
        { title: "02 How the Pieces Move", topics: ["How the rook, bishop, queen, knight, and king move", "How pieces move straight, diagonally, sideways, and in different directions", "How the knight makes its special jump", "How the bishop stays on the same square color", "How to recognize the different movement patterns of each piece", "How to practice piece movements through simple chess games", "Understanding the basic relative value of the pieces"] },
        { title: "03 Attack and Capture", topics: ["What it means to attack an enemy piece", "How to capture an enemy piece correctly", "Understanding that capturing is not compulsory", "How different pieces capture according to their movement", "How the knight can jump over pieces while capturing", "How to identify whether a piece is safe or vulnerable", "How to attack an opponent’s piece safely", "Understanding that your attacking piece can also be captured", "How multiple pieces can interact and influence each other"] },
        { title: "04 The Pawn", topics: ["How the pawn moves forward", "When a pawn can move one or two squares", "How the pawn captures diagonally", "Why the pawn cannot move backwards", "How a pawn reaches the other side of the board", "What pawn promotion means", "How to choose a new piece when a pawn promotes", "How to set up the chess pieces in their starting position", "How to identify the correct direction for White and Black pawns"] },
        { title: "05 Protecting", topics: ["What it means to defend a chess piece", "How to recognize when a piece is under attack", "How to move an attacked piece to safety", "How to protect a piece with another piece", "How to capture the attacking piece", "How to block an attack when possible", "How to identify protected and unprotected pieces", "How to think about the opponent’s possible moves", "How to defend without losing another piece"] },
        { title: "06 Check & Escaping Check", topics: ["What check means in chess", "How to recognize when the king is under attack", "Why a king cannot remain in check", "How to get out of check", "How to escape check by moving the king", "How to capture the checking piece", "How to block a check by interposing a piece", "Why two kings cannot stand next to each other", "Why the king should never be captured during a game"] },
        { title: "07 Checkmate: Part 1", topics: ["What checkmate means in chess", "How to recognize when a king is completely trapped", "How to deliver checkmate", "How to control the escape squares around the king", "How one piece can support another piece to create checkmate", "How the king’s own pieces can block its escape", "How different pieces can work together to deliver mate", "How to identify simple mating patterns", "How checkmate ends the game and determines the winner"] },
        { title: "08 Checkmate: Part 2", topics: ["How pieces work together to deliver checkmate", "How to control the king’s escape squares", "Understanding the roles of the guard and the chaser", "How to deliver check while restricting the king", "How different pieces can complement each other", "How to avoid opening new escape squares when giving check", "How to recognize more advanced mating patterns", "How to find checkmate in one move in more complex positions"] },
        { title: "09 Castling", topics: ["What castling means in chess", "How to perform kingside and queenside castling", "How castling helps protect the king", "How castling brings the rook into play", "Understanding the difference between the kingside and queenside", "When castling is allowed", "When castling is not allowed", "How to check whether a position is safe for castling"] },
        { title: "10 Smart Exchanges", topics: ["Understand the basic value of each chess piece", "Learn why some pieces are more valuable than others", "Understand what a piece exchange means", "Learn how to trade pieces of similar value", "Identify profitable exchanges", "Compare different captures before making a move", "Learn why winning more material is usually better", "Understand the special meaning of “the exchange”"] },
        { title: "11 Double Pressure", topics: ["Understand how a piece can be attacked more than once", "Recognize when a piece is not sufficiently defended", "Learn how two attackers can work together against one defender", "Count attackers and defenders before making a capture", "Choose the correct order of captures to win material", "Understand that not every double attack leads to a material gain", "Learn how double pressure can sometimes lead to checkmate", "Recognize double pressure along ranks, files, and diagonals"] },
        { title: "12 Understanding Draw", topics: ["What a draw means in chess", "How a chess game can end without a winner", "What stalemate means", "How to tell the difference between checkmate and stalemate", "How to identify when a player has no legal move", "Why stalemate results in a draw", "How to avoid accidentally stalemating an opponent when winning", "Understanding that every piece must be unable to move for stalemate to occur"] },
        { title: "13 Mating with Queen", topics: ["How to checkmate with a queen and king", "Why the queen cannot checkmate the king alone", "How the king helps the queen deliver checkmate", "How to recognize common queen mating patterns", "How to bring the king closer to support the queen", "How to restrict the opponent’s king step by step", "How to drive the enemy king toward the edge of the board", "How to avoid stalemate while preparing checkmate", "How to deliver checkmate efficiently with king and queen"] },
        { title: "14 The Pawn: En Passant", topics: ["What en passant means in chess", "When a pawn can capture en passant", "Why en passant is a special type of pawn capture", "How a pawn captures an opponent’s pawn that has moved two squares", "Why the en passant capture must be made immediately", "How to recognize when en passant is legal", "How to distinguish en passant from a normal pawn capture"] },
        { title: "15 Chess Notation", topics: ["What chess notation means and why it is used", "How to write down chess moves using square names", "How to use the correct letter for each chess piece", "How to record pawn moves and captures", "How to record check, checkmate, promotion, and castling", "How to write down your own chess games and solutions", "How to record captures using the correct notation symbols"] }
      ]
    },
    {
      id: "beginner",
      title: "Beginner",
      description: "Building on the foundation with intermediate tactics, checkmate patterns, special moves, and basic strategies.",
      duration: "3-6 Months",
      ageGroup: "All Ages",
      fees: "Contact for details",
      chapters: [
        { title: "01 Piece Activity", topics: ["What Is Piece Activity?", "Knight Activity", "Bishop Activity", "Rook and Queen Activity", "Controlling the Center", "Piece Coordination", "Restricting Enemy Pieces", "Improving Piece Placement", "Creating Threats Through Activity"] },
        { title: "02 Attack Targets", topics: ["Understanding Attack Targets", "Attacking the King", "Attacking Pieces", "Attacking Squares", "Double Attacks on Material", "Attacking Mating Squares", "Pressure and Initiative"] },
        { title: "03 Double Attack: Queen", topics: ["Understanding Queen Double Attacks", "King and Material Double Attacks", "Double Attacks on Pieces", "Material and Mating Threats", "Finding the Best Queen Square", "Avoiding Bad Double Attacks", "Defending Against Queen Double Attacks"] },
        { title: "04 The Pin", topics: ["Understanding the Pin", "Absolute Pins", "Relative Pins", "Creating Pins", "Pins on Ranks, Files and Diagonals", "Exploiting a Pin", "When a Pinned Piece Can Move", "Spotting Pins in Real Games"] },
        { title: "05 Basic Checkmates", topics: ["Checkmating with Two Rooks (Ladder Mate)", "Checkmating with a Queen", "Common Mistakes in Basic Checkmates"] },
        { title: "06 Removing the Defender: Win Material", topics: ["Understanding Defenders", "Capturing the Defender", "Chasing Away the Defender", "Luring Away the Defender", "Overloaded Defenders", "Is It Safe?", "Finding Defender Removal Tactics"] },
        { title: "07 Opening Golden Rules", topics: ["The Three Golden Rules", "Developing Your Pieces", "Controlling the Center", "Keeping the King Safe", "Common Opening Mistakes", "Putting It All Together"] },
        { title: "08 Mate in Two", topics: ["Understanding Mate in Two", "Chasing and Guarding", "Removing Flight Squares", "Building a Mating Pattern", "Forcing Moves", "Finding Mate in Two"] },
        { title: "09 Double Attack: Knight Forks", topics: ["Understanding Knight Forks", "King and Material Forks", "Piece and Piece Forks", "Forking Important Squares", "Finding the Right Fork Square", "Searching for Knight Forks", "Knight Fork Traps and Tricks"] },
        { title: "10 Rook Mate", topics: ["Understanding Rook Mate", "King and Rook Cooperation", "Driving the King to the Edge", "Shrinking the Prison", "Waiting Moves", "Delivering the Rook Mate", "Common Mistakes and Practical Training"] },
        { title: "11 Double Attack: RBPK", topics: ["Understanding Double Attacks with RBPK", "Rook Double Attacks", "Bishop Double Attacks", "Pawn Double Attacks", "King Double Attacks", "Double Attacks with Two Pieces", "Using Check to Create Double Attacks", "The Double Attack Search Checklist"] },
        { title: "12 Discovered Attack", topics: ["Understanding Discovered Attacks", "Batteries: Front Piece and Back Piece", "Creating Batteries", "Discovered Attacks on Material", "Discovered Check and Mating Threats", "Moving the Front Piece", "When Discovered Attacks Fail", "Finding Discovered Attacks", "Defending Against Discovered Attacks"] },
        { title: "13 Defending Checkmate", topics: ["Recognizing Mate Threats", "Defending by Capturing", "Defending by Blocking", "Defending by Moving the King", "Defending Key Squares", "Pawn Defences and Escape Squares", "Defending with Counterplay", "Sacrificing Material to Survive", "Finding the Only Move", "Real Defence vs False Defence"] },
        { title: "14 Complete Your Opening", topics: ["When Is the Opening Complete?", "Completing Piece Development", "Connecting the Rooks", "Finding the Right Square for the Queen", "Understanding Tempo", "Common Opening Mistakes", "Weak Squares in the Opening", "Opening Completion Checklist"] }
      ]
    },
    {
      id: "intermediate",
      title: "Intermediate",
      description: "Transitioning to tactical thinking, basic planning, positional play, and complex endgames.",
      duration: "6 Months",
      ageGroup: "All Ages",
      fees: "Contact for details",
      chapters: [
        { title: "01 Discovered & Double Check", topics: ["Discovered Attack vs Discovered Check", "Batteries and Line Attacks", "Creating Discovered Checks", "Winning Material with Discovered Checks", "Driving the King into Danger", "Discovered Checks and Checkmate", "Understanding Double Check", "Mating Nets with Double Check", "Choosing the Best Discovery"] },
        { title: "02 Attacking Pinned Pieces", topics: ["Evaluating the Pin", "Protected and Unprotected Pins", "Attacking the Pinned Piece", "Adding More Attackers", "Preventing Escapes and Counterplay", "When the Pin Does Not Work", "Hidden Threats from Pinned Pieces", "Cross-Pins and Advanced Pin Tactics", "Spotting Winning Pin Opportunities"] },
        { title: "03 Breaking King Shelter", topics: ["Understanding King Shelter", "Creating Access", "Breaking the Pawn Shield", "Sacrificing for Access", "Forcing Captures and Exchanges", "Opening Files Against the King", "Opening Diagonals Against the King", "Luring Defenders Away", "Access and Checkmating Attacks"] },
        { title: "04 Pawn Endgame: Square Rule", topics: ["Introduction to Pawn Endgames", "Understanding the Square Rule", "Drawing the Square", "Inside or Outside the Square?", "Special Cases and Exceptions", "When the Square Rule Fails", "King Support and Shouldering", "Pawn Push or King Move?", "Common Pawn Endgame Mistakes", "Practical Square Rule Exercises"] },
        { title: "05 Removing the Defender: Win the Mate", topics: ["Defenders in Checkmating Attacks", "Capturing the Defender", "Luring Away the Defender", "Chasing Away the Defender", "Defenders Doing Double Duty", "Sacrificing for Mate", "Mate Over Material", "Forcing the Defense", "Finding Defender Removal Mates"] },
        { title: "06 Double Attack: Surviving", topics: ["Recognizing the Double Attack", "Defending by Moving Away", "Defending by Protecting", "Defending by Capturing or Exchanging", "Defending by Interposing", "Combining Defensive Methods", "Counterattack as Defense", "Counterattacks by Check, Pin, and Threat", "King Safety vs Material", "Common Defensive Mistakes"] },
        { title: "07 Simple Chess Plans", topics: ["What Is a Chess Plan?", "Activity and Vulnerability", "Pawn Structure Basics", "Doubled Pawns and Pawn Duos", "Capturing Toward the Center", "Piece Improvement and Manoeuvres", "Division of Labour Between Pieces", "Activating the Rooks", "Creating Pressure Through Improvement", "Turning Small Advantages into Plans"] },
        { title: "08 Saving the Draw", topics: ["Draws Beyond Stalemate", "Draw by Insufficient Material", "Two Knights vs Lone King", "Stalemate as a Defensive Weapon", "Perpetual Check", "Repetition and Perpetual Attack", "Draw by Agreement", "Saving Lost Positions", "Win or Draw?"] },
        { title: "09 X-Ray Attacks", topics: ["Understanding X-Ray Attacks", "X-Ray Check", "X-Ray Attacks on Pieces", "X-Ray with Rooks", "X-Ray with Bishops and Queens", "Winning Material with X-Rays", "X-Ray Protection", "X-Ray and Double Attacks", "Spotting X-Rays in Real Games"] },
        { title: "10 Opening as a Weapon", topics: ["Opening Principles Revisited", "Attacking the Center", "Development Over Material", "Understanding Tempo", "Sacrificing for Activity", "Defending and Attacking Central Pawns", "Ignore or Respond?", "The Problem with Early Queen Moves", "Choosing an Opening Plan", "Playing for Initiative"] },
        { title: "11 Defending the Pin", topics: ["Evaluating the Pin", "Defending by Interposing", "Defending by Capturing the Attacker", "Defending the Pinned Piece", "Moving the Pinned Piece Safely", "Counterattack as Defense", "Counterattacks by Check and Threat", "Discovered Attacks and Pin Breaking", "Passive Defense vs Active Counterplay", "Defending Pins in Real Games"] },
        { title: "12 Piece Mobility", topics: ["Understanding Piece Mobility", "Value, Position, and Function", "Pieces on the Edge", "Blocked and Restricted Pieces", "Temporary vs Permanent Mobility Problems", "Piece Entrapment", "Trapping Pieces with Pawns and Coordination", "Shutting a Piece Out of the Game", "Central Pieces with No Escape", "Converting Mobility into Advantage"] },
        { title: "13 Pawn Endgame: Key Squares (Part 1)", topics: ["Introduction to Key Squares", "Finding the Key Squares", "Winning and Drawing Positions", "The King in Front of the Pawn", "Reaching a Key Square", "The 6th-Rank Winning Position", "Correct Pawn Timing", "Mistakes That Change the Result", "The Special Case of Rook Pawns"] },
        { title: "14 Pinned Pieces Weak", topics: ["Why Pinned Pieces Become Weak", "Pin to the King", "Pin to Material and Key Squares", "Pinned Pieces Cannot Recapture", "Pinned Pieces Cannot Defend", "Winning Material Through Pinned Defenders", "Pins Against Squares and Lines", "Pin and Capture Combinations", "Pin and Double Attack Combinations", "Pins in Mating Attacks", "Spotting Weak Defenders"] },
        { title: "15 Spot the Threat", topics: ["Thinking Like Your Opponent", "Threats Against Pieces", "Threats Against the King", "Mate in One and Mate in Two Threats", "Weak Defenders and Hidden Dangers", "Batteries, Alignments and Fork Threats", "Defending Critical Squares", "Choosing the Right Defensive Move", "Defending Multiple Threats", "Counterattack as Defense", "Opening and Development Threats", "Promotion Threats and Special Promotions", "Defense or Attack?", "The Threat-Checking Routine"] },
        { title: "16 Pawn Endgame: Key Squares (Part 2)", topics: ["Key Squares Revisited", "Attacking and Defending Key Squares", "Introduction to Zugzwang", "Forcing the Enemy King to Yield", "Waiting Positions", "King Distance and Opposition", "Changing Key Squares", "Sacrificing a Pawn to Draw", "Rook Pawn Exceptions", "Practical Key-Square Endgames"] }
      ]
    },
    {
      id: "advanced",
      title: "Advanced",
      description: "Refining skills for competitive play and high-level tournament performance. Covers Grandmaster Games Analysis, Advanced Calculation, Specialized Openings, and Tournament Preparation.",
      duration: "Ongoing",
      ageGroup: "Rated Players",
      fees: "Contact for details",
      chapters: [
        { title: "01 Time Is Power", topics: ["Why Time Matters", "Recognizing a Lead in Development", "Exploiting Slow Development", "Opening the Centre", "Opening Lines for Attack", "Gambits and Dynamic Play", "Tempo and Piece Targets", "Turning Development into Attack", "Choosing the Right Plan", "Opening Calculation and Decision Making"] },
        { title: "02 Removing the Defender: Interference", topics: ["Understanding Interference", "Interference vs Interposition", "Blocking Files, Ranks and Diagonals", "Interference by Check", "Interference by Attack", "Winning Material with Interference", "Interference in Mating Attacks", "Combining Interference with Other Tactics", "Sacrificial Interference", "Finding the Key Defender", "Interference in Practical Play", "The Interference Search Process"] },
        { title: "03 Double Attack: Luring", topics: ["Understanding Luring", "Why Direct Double Attacks Fail", "Finding the Target Square", "Luring the King", "Luring Defenders", "Luring by Sacrifice and Exchange", "Luring for Knight and Queen Forks", "Luring for Discovered Attacks", "Combining Luring with Other Tactics", "Reversing the Move Order", "Practical Luring Patterns", "The Luring Search Process"] },
        { title: "04 Removing the Defender: Blocking", topics: ["Understanding Blocking", "Blocking vs Interposing", "Blocking Defensive Lines", "Blocking Flight Squares", "Blocking with Different Pieces", "Forced Blocking", "Blocking Through Sacrifice", "Blocking and Defender Elimination", "Blocking and Tactical Combinations", "Blocking in Checkmating Attacks", "Smothered Mate Patterns", "Finding Blocking Opportunities"] },
        { title: "05 Thinking Ahead", topics: ["What Is Thinking Ahead?", "Visualization Basics", "Candidate Moves", "Predicting the Opponent", "Building Variations", "Checks, Captures and Threats", "Spotting Tactical Clues", "Evaluating the Final Position", "Avoiding Calculation Mistakes", "Active vs Defensive Thinking", "The Thinking Process", "Training Visualization and Focus"] },
        { title: "06 Pin: Front & Back", topics: ["Understanding Front and Back Pieces", "Why Placement Matters", "Creating the Front Piece", "Creating the Back Piece", "Luring Pieces into a Pin", "Forcing Pieces into a Pin", "Creating Pins Through Sacrifices", "Pins After Exchanges and Captures", "Exploiting the Pin", "Pins and Mating Attacks", "When Direct Pins Fail", "Building Pins Step by Step"] },
        { title: "07 Pawn Endgame: Passed Pawns", topics: ["Understanding Passed Pawns", "Why Passed Pawns Matter", "Creating a Passed Pawn", "Preventing a Passed Pawn", "Stopping a Passed Pawn", "Supporting Promotion", "Removing the Defender", "Promotion Techniques", "Passed Pawns as Tactical Weapons", "Advanced Promotion Methods", "Defending Against Promotion", "Special Passed Pawn Endgames", "Life After Promotion", "Practical Passed Pawn Play"] },
        { title: "08 Double Attack: Eliminate the Defender", topics: ["Why Double Attacks Fail", "Finding the Key Defender", "Eliminating the Defender by Capture", "Eliminating the Defender by Sacrifice", "Luring Defenders Away", "Chasing Defenders Away", "Interference and Blocking", "Defender Removal for Forks and Checks", "Defender Removal for X-Rays and Discoveries", "Combining Elimination and Double Attack", "Choosing the Right Method", "The Elimination Search Process"] },
        { title: "09 Magnet Checkmate", topics: ["Understanding the Magnet Tactic", "Finding the Final Mate First", "Forcing the King to a Target Square", "Rook Sacrifice Magnets", "Queen Sacrifice Magnets", "Destroying King Safety", "Controlling Escape Squares", "Magnet and Piece Coordination", "Magnet and Tactical Combinations", "Magnet and Forcing Checks", "Choosing the Correct Sacrifice", "When the Magnet Does Not Work", "Practical Magnet Checkmates"] },
        { title: "10 Weak Pawns & Strong Squares", topics: ["Understanding Weak Pawns", "Types of Weak Pawns", "When Pawn Moves Create Weaknesses", "Defending Weak Pawns", "Weak Pawns and Piece Mobility", "Weak Pawns in Endgames", "Understanding Strong Squares", "Creating and Maintaining Strong Squares", "Placing Pieces on Strong Squares", "Weak Pawns Create Strong Squares", "Structure vs Activity", "Applying Pressure to Weak Pawns", "Visual Evaluation of Positions"] },
        { title: "11 Rook Endgame: Passed Pawns", topics: ["Understanding Rook Endgames", "Activating the King", "Rook and King Coordination", "Cutting Off the Enemy King", "Supporting Pawn Advances", "Creating a Passed Pawn", "Connected Passed Pawns", "Building a Bridge", "When to Exchange Rooks", "Sacrificing for Activity", "Special Passed Pawn Cases", "Defensive Resources", "Step-by-Step Conversion", "Practical Rook Endgames"] },
        { title: "12 Double Attack: Chasing & Aiming", topics: ["Understanding Chasing and Aiming", "Why the Double Attack Doesn't Work Yet", "Chasing the King", "Chasing Pieces into Danger", "Knight Forks Through Chasing", "Understanding Aiming", "Aiming with Tempo", "Knight Aiming Techniques", "Queen Aiming Techniques", "Combining Chasing and Aiming", "Mixed Tactical Patterns", "Hidden Double Attacks", "Exploiting Unprotected Pieces", "The Chasing & Aiming Search Process"] },
        { title: "13 Attacking the Castled King", topics: ["Understanding the Castled King", "When an Attack Is Possible", "Gaining Access to the King", "Opening Lines by Sacrifice", "Eliminating Key Defenders", "Using Tactical Attack Tools", "Bringing New Attackers", "Restricting Escape Squares", "Rook and Bishop Mating Patterns", "Rook and Knight Attacks", "Bishop and Knight Coordination", "Combining Attacking Ideas", "The Complete Attacking Sequence", "Practical Castled-King Attacks"] },
        { title: "14 Seventh Rank Power", topics: ["Understanding the Seventh Rank", "Rook Activity on the Seventh Rank", "Restricting the Enemy King", "Attacking Pawns and Weaknesses", "Double Rooks on the Seventh Rank", "Removing Defenders", "Rook and Bishop Batteries", "Repeated Threats and Discoveries", "Using Opponent Pieces as Blockers", "Mating Patterns on the Seventh Rank", "Perpetual Check with Rooks", "Choosing the Correct Rook", "Activity vs Safety", "Practical Seventh-Rank Attacks"] },
        { title: "15 Pawn Endgame: Strategy", topics: ["Understanding Pawn Endgame Strategy", "King Activity First", "Giving Up Pawns for Activity", "Outside Passed Pawns", "King Activity vs Passed Pawn", "Creating Passed Pawns Correctly", "The Candidate Pawn Principle", "Reserve Tempo", "Protected Passed Pawns", "Pawn Structure Discipline", "Shielding and Restricting the King", "Zugzwang as a Weapon", "Key Squares Revisited", "Converting Small Advantages", "Practical Pawn Endgame Strategy"] },
        { title: "16 Double Attack: Clearing the Path", topics: ["Understanding Clearance", "Why the Double Attack Doesn't Work", "Square Clearance", "Line Clearance", "Diagonal Clearance", "File and Rank Clearance", "Clearing with Tempo", "Tactical Exchanges for Clearance", "Clearance for Forks", "Clearance for Discoveries and X-Rays", "Layered Threats", "Identifying Blocking Pieces", "Combining Clearance with Other Themes", "The Clearance Search Process"] },
        { title: "17 Queen vs Pawn", topics: ["Understanding Queen vs Pawn Endgames", "Why the Queen Needs Help", "Controlling the Promotion Square", "Stopping Promotion", "Bringing the King Closer", "Dangerous and Harmless Pawns", "Winning Pawn Types", "Difficult Pawn Types", "Stalemate Traps", "Drawing Techniques", "Precision and Move Order", "Converting the Advantage", "Practical Queen vs Pawn Positions"] }
      ]
    },
    {
      id: "master",
      title: "Master",
      description: "Expert-level training for rated players aiming for mastery. Includes Tailored Coaching, Psychological Resilience, Deep Opening Preparation, and Complex Endgame Analysis.",
      duration: "Flexible",
      ageGroup: "Rated Players",
      fees: "Contact for details",
      chapters: [
        { title: "01 Material vs Time", topics: ["Understanding Material and Time", "What Is Time in Chess?", "Lead in Development", "The King in the Center", "Initiative vs Material", "Sacrificing for Time", "Opening the Center", "Punishing Slow Development", "Time Creates Attack", "Material Returns", "Time in Endgames", "Evaluating Material vs Time"] },
        { title: "02 Quiet Moves & Zugzwang", topics: ["Understanding Quiet Moves", "Why Checks Are Not Always Best", "Preparing Checkmate", "Removing Escape Squares", "Understanding Zugzwang", "Creating Zugzwang", "Quiet Moves in Endgames", "Quiet Moves in Mating Attacks", "Combining Tactical Themes", "Mate in Two", "Mate in Three", "Creative Checkmate Construction", "Quiet Move Search Process"] },
        { title: "03 Pawn Endgame: Breakthroughs", topics: ["Understanding Pawn Breakthroughs", "Pawn Majorities", "Sacrifice to Create a Passed Pawn", "Fixed Pawn Structures", "Correct Move Order", "Pure Pawn Breakthroughs", "King Support and Opposition", "Square of the Pawn Revisited", "Classic Breakthrough Patterns", "Defensive Techniques", "Complex Breakthroughs", "Pawn Races After the Breakthrough", "Converting the Breakthrough", "Practical Breakthrough Positions"] },
        { title: "04 Using Pawns", topics: ["Pawns as Strategic Tools", "Understanding Pawn Structure", "Strong and Weak Pawns", "Strong Squares and Outposts", "Pawn and Piece Interaction", "Understanding Pawn Tension", "Timing Pawn Breaks", "Demolishing Pawn Structures", "Creating Weaknesses", "Strategic Pawn Moves", "Strategic Pawn Exchanges", "Activity vs Structure", "Choosing the Right Pawn Plan", "Practical Pawn Strategy"] },
        { title: "05 Pawn Endgame: Pawn Races", topics: ["Understanding Pawn Races", "Counting Steps Correctly", "Square of the Pawn Revisited", "King Assistance", "King Blocking and Shielding", "Promoting First Is Not Enough", "Promotion with Check", "X-Ray and Tactical Promotion Ideas", "Mating Nets After Promotion", "Defensive Resources", "Simultaneous Promotion", "Queen vs Pawn Race Outcomes", "Full-Board Calculation", "Practical Pawn Race Positions"] },
        { title: "06 Seventh Rank Domination", topics: ["Understanding Seventh Rank Domination", "Rook Domination", "Absolute vs Partial Control", "Restricting the Enemy King", "Attacking Pawns from the Seventh Rank", "Passed Pawn Activation", "Sacrificing Material for Domination", "Activity vs Material", "King Activation", "Defending Against Seventh Rank Invasions", "Preparing the Invasion", "Converting Domination into Victory", "Winning and Drawing Models", "Endgame Simulation and Practice"] },
        { title: "07 Discovered Attack", topics: ["Understanding Discovered Attacks", "The Battery Structure", "Building the Battery", "Creating Lines for the Battery", "Clearing the Path", "Eliminating the Defender", "Luring and Chasing", "Aiming the Discovery", "Discovered Check", "Winning Material with Discoveries", "Checkmate Through Discoveries", "Creating a Battery from Nothing", "The Discovery Search Process", "Practical Discovery Combinations"] },
        { title: "08 Pin: Exploitation", topics: ["Understanding Pin Exploitation", "Front Piece and Back Piece", "Attacking the Pinned Piece", "Pinned Pieces as Weak Defenders", "Aiming Before the Pin", "Aiming and Attacking the Pinned Piece", "Eliminating Defenders Before the Pin", "Pin and Defender Elimination", "Clearance and Pin Creation", "Luring and Chasing into Pins", "Pin and Fork Combinations", "Pin and Discovered Attack Combinations", "Pin and Mate Patterns", "Pin Exploitation Search Process"] },
        { title: "09 Opening: Structure & Tension", topics: ["Understanding Opening Structures", "Pawns and Pieces Working Together", "Central Control", "Understanding Tension", "Maintaining Tension", "Releasing Tension", "Creating Targets", "Development with Tempo", "Structure vs Flexibility", "Demolishing Pawn Structures", "Common Tension Mistakes", "Transitioning to the Middlegame", "Finding the Right Opening Plan", "Practical Opening Structures"] },
        { title: "10 Rook vs Pawn: Rules", topics: ["Understanding Rook vs Pawn Endgames", "King and Rook Cooperation", "Stopping Promotion", "Rook Placement Behind the Pawn", "Rook Placement on the Promotion Square", "Choosing the King's Route", "Tempo and Activity", "Shielding Techniques", "Horizontal Cut-Off", "When the Cut-Off Fails", "Knight Promotion Tricks", "Standard Winning Rules", "Standard Drawing Rules", "Practical Rook vs Pawn Positions"] },
        { title: "11 Strong Square", topics: ["Understanding Strong Squares", "How Strong Squares Are Created", "Pawn Control and Weak Squares", "Creating Strong Squares", "Eliminating Defenders", "Luring Defenders Away", "Choosing the Right Occupier", "Timing the Occupation", "Defending the Strong Square", "Exchanges and Replacement", "Common Occupation Mistakes", "Strong Squares as Strategic Anchors", "Turning Strong Squares into Plans", "Practical Strong Square Positions"] },
        { title: "12 Defending: Active Defense", topics: ["The Defensive Mindset", "Spotting the Real Threat", "Defensive Decision Making", "Defending Against Checkmate", "Defending Material", "Defending Against Passed Pawns", "Counterattack as Defense", "Blocking, Pinning, and Exchanging", "Active Piece Defense", "Visualization in Defense", "Calculating Forcing Lines", "Saving Difficult Positions", "Drawing Mechanisms Under Pressure", "Practical Active Defense"] },
        { title: "13 Rook Endings: Technique & Survival", topics: ["Understanding Rook Endings", "King and Rook Coordination", "Active vs Passive Rooks", "The Principle of Activity", "Building a Bridge (Lucena Method)", "Checking from Behind", "Checking from the Side", "Defensive Rook Endings", "Short Side vs Long Side Defense", "Cutting Off the King", "Passed Pawn Technique", "Tactical Resources in Rook Endings", "Rook Vulnerability", "Practical Winning and Drawing Positions"] },
        { title: "14 King Attack Techniques", topics: ["Understanding King Attacks", "Attackers vs Defenders", "Identifying Weak Kings", "Bringing Pieces into the Attack", "Eliminating Defenders", "Clearing Lines to the King", "Forcing Moves", "Sacrifices for Attack", "The Greek Gift Sacrifice", "Continuing After the Sacrifice", "Typical Mating Patterns", "Choosing the Best Continuation", "Converting Pressure into Checkmate", "Practical King Attacks"] },
        { title: "15 Open File Control", topics: ["Understanding Open Files", "Why Rooks Love Open Files", "Creating Open Files", "Sacrificing to Open a File", "Safe File Creation", "Occupying the Open File", "Fighting for File Control", "Eliminating the Defender", "Preparation Before Occupation", "Invasion Squares", "Outposts on Open Files", "Converting File Control", "Open Files and Passed Pawns", "Practical Open File Positions"] },
        { title: "16 The Art of Drawing", topics: ["Understanding Draws", "When Winning Is Impossible", "Insufficient Material", "Two Knights vs King", "Exchanging Dangerous Pieces", "Understanding Stalemate", "Tactical Stalemates", "Wrong Bishop Endings", "Defensive King Placement", "Finding the Correct Route", "Fortress Concepts", "Turning Losses into Draws", "Winning vs Drawing Recognition", "Changing Plans After Evaluation", "Practical Drawing Techniques"] }
      ]
    },
    {
      id: "champion",
      title: "Champion",
      description: "Elite level coaching for national and international level champions. Customized intensive training with Grandmasters.",
      duration: "Flexible",
      ageGroup: "Professional Players",
      fees: "Contact for details",
      chapters: [
        { title: "01 King in the Center", topics: ["Understanding Centralized Kings", "Development Advantage as a Weapon", "Why the Center Must Be Opened", "The e-File and d-File Attack", "Dangerous Diagonals", "Development with Tempo", "Piece Coordination Against the King", "Preventing Castling", "Sacrificing to Open Lines", "Typical Central-King Sacrifices", "Calculating Attack Validity", "Common Defensive Mistakes", "Converting Pressure into Victory", "Model Games: Kings in the Center"] },
        { title: "02 Passed Pawn Power", topics: ["Understanding Passed Pawns", "When a Passed Pawn Wins", "When a Passed Pawn Must Be Sacrificed", "King Support and Escorting", "Eliminating and Restricting Defenders", "Advancing with Tempo", "Tactical Helpers for Promotion", "Keeping Defenders at a Distance", "Pins Against Passed Pawns", "Promotion Traps", "Passed Pawns in the Opening", "Passed Pawns in the Middlegame", "Bishop vs Passed Pawns", "Knight vs Passed Pawns", "Timing, Tempo and Zugzwang", "Passed Pawn Mastery"] },
        { title: "03 Strategic Mini-Plans", topics: ["What Is Strategy?", "Why Long Plans Often Fail", "The Three Strategic Goals", "Improving Piece Activity", "Piece Cooperation", "Identifying Vulnerable Pieces", "Improving the Worst-Placed Piece", "Supporting the Best Piece", "Strong Squares and Outposts", "Attacking the Weakest Point", "Creating New Weaknesses", "Reducing Your Own Weaknesses", "Using Tension Strategically", "Restricting Opponent Activity", "Mini-Plan Thinking", "Strategic Mastery in Practice"] },
        { title: "04 Piece Mobility", topics: ["Understanding Mobility", "Mobility in the Opening", "Recognizing Trapped Pieces", "The Trapping Process", "Attraction Techniques", "Eliminating the Defence", "Chasing Pieces", "Targeting Escape Squares", "Blocking Techniques", "Clearing for Traps", "Central Piece Traps", "Tactical Restrictions", "Early Queen Adventures", "Trapping the Queen", "Endgame Trapping Techniques", "Mobility and Tactical Motifs", "Encircling Pieces", "Long-Term Piece Restriction", "Mobility Mastery"] },
        { title: "05 Drawing Techniques", topics: ["Understanding Draws", "Insufficient Material", "Removing Mating Potential", "Wrong Bishop Endings", "Stalemate Fundamentals", "Sacrificial Stalemates", "Sudden Stalemate Tricks", "Perpetual Check", "Perpetual Attack", "Threefold Repetition", "Fortress Fundamentals", "Building a Fortress", "Fortress vs Zugzwang", "Practical Fortress Examples", "Defensive Exchanges", "The 50-Move Rule", "Choosing the Right Drawing Method", "Drawing Technique Mastery"] },
        { title: "06 Opening Study Method", topics: ["Why Study Openings?", "Opening, Middlegame and Endgame Connection", "Common Opening Study Mistakes", "Choosing Quality Opening Resources", "Role of Coaches and Trainers", "Main Lines and Improvement", "Learning a New Opening", "Understanding Pawn Structures", "Studying Model Games", "Typical Opening Plans", "Practising New Openings", "Building an Opening Repertoire", "Updating and Changing Repertoires", "Keeping Up With Opening Theory", "Typical Opening Tactics", "Playing According to Opening Ideas", "Opening Principles With Flexibility", "Recognizing Bad Development", "Building a Personal Opening System"] },
        { title: "07 Tactical Thinking", topics: ["What Tactics Really Are", "Recognizing Tactical Targets", "The Tactical Thinking Process", "Finding Candidate Moves", "Mate as a Tactical Goal", "Common Mating Patterns", "Double Attacks", "Discovered Attacks and Checks", "X-Ray Attacks", "Mixed Tactical Combinations", "Understanding Pins Deeply", "Eliminating Defenders", "Interference and Blocking", "Preparation Before Execution", "Quiet Moves in Tactics", "The Tactical Awareness Checklist", "Tactical Calculation and Verification", "Tactical Thinking Mastery"] },
        { title: "08 Pawn Endgame: Mastery", topics: ["Why Pawn Endings Matter", "Revisiting Core Pawn Ending Themes", "Understanding Key Squares Deeply", "Attacking and Defending Key Squares", "Tempo and Waiting Moves", "Triangulation and Zugzwang", "Shouldering Off the Enemy King", "Advanced Shouldering Techniques", "Understanding the Rook Pawn", "King Routes and Distance Illusions", "Calculating Pawn Races", "Promotion Tactics", "The Réti Manoeuvre", "Breakthrough Fundamentals", "Advanced Breakthrough Techniques", "Defensive Resources in Pawn Endings", "Evaluating Pawn Endings", "The Pawn Ending Checklist", "Pawn Endgame Mastery"] },
        { title: "09 Bishop vs Knight", topics: ["The Core Truth", "Understanding the Bishop", "Understanding the Knight", "Pawn Structure Determines Piece Strength", "Good Bishops and Bad Bishops", "Playing Against a Bad Bishop", "Knight Outposts and Centralisation", "Improving Minor Pieces Through Exchanges", "Bishops in the Middlegame", "Knights in the Middlegame", "Minor Pieces in the Endgame", "Knight Dominating a Bishop", "Bishop Dominating a Knight", "Passed Pawns and Minor Pieces", "Common Strategic Mistakes", "The Bishop vs Knight Checklist", "Bishop vs Knight Mastery"] },
        { title: "10 Finishing the Attack", topics: ["The Four Steps of a Successful Attack", "Preparing the Attack", "Bringing Pieces into the Attack", "Understanding Access to the King", "Attacking the Pawn Shield", "The g-Pawn Weakness", "Eliminating Defenders", "Coordinating the Attack", "Using the Correct Attacking Piece", "Knowing When Not to Sacrifice", "Forcing Weaknesses", "Opposite-Coloured Bishops and Attack", "Battery Attacks", "Bringing the Last Piece", "Calculating the Finish", "Building a Mating Net", "Common Attacking Mistakes", "Finishing the Attack Checklist", "Attack Conversion Mastery"] },
        { title: "11 Winning the Endgame", topics: ["Why Winning Won Positions Is Difficult", "Converting a Material Advantage", "Exchange Principles", "Protecting Critical Pawns", "Correct Piece Placement", "Winning Through Endgame Attacks", "Endgame Tactical Motifs", "King Safety in the Endgame", "Understanding Liquidation", "Liquidating Into Winning Pawn Endings", "Correct Order of Exchanges", "Avoiding Conversion Mistakes", "Zugzwang as a Winning Weapon", "Triangulation Techniques", "Defending Against Passed Pawns", "Stalemate Awareness", "Endgame Conversion Discipline", "Endgame Conversion Checklist", "Winning the Endgame Mastery"] },
        { title: "12 Mastering Bishops", topics: ["Understanding Bishops", "Bishop Activity and Mobility", "Good Bishop vs Bad Bishop", "Activating a Bad Bishop", "Playing Against a Bad Bishop", "Activity Over Pawn Colour", "Bishops in the Middlegame", "Bishops in the Endgame", "Same-Coloured Bishop Endgames", "Passed Pawns with Same-Coloured Bishops", "Opposite-Coloured Bishops", "Defending with Opposite-Coloured Bishops", "Winning with Opposite-Coloured Bishops", "Bishop vs Passed Pawns", "Short and Long Diagonals", "Zugzwang in Bishop Endgames", "Defensive Techniques in Bishop Endgames", "Bishop Endgame Evaluation Checklist", "Bishop Mastery"] },
        { title: "13 Practical Defence", topics: ["Understanding Defence", "Defending Against Mate", "Eliminating the Attacking Piece", "Creating Escape Squares", "Stopping the Attack", "Using Pawns as Defensive Shields", "Swapping Off Attacking Pieces", "Choosing the Right Exchange Sequence", "Bringing Defenders Into the Game", "Queen and Rook Defence", "Counterattack as Defence", "Defending Against Tactical Threats", "Defending Against Pins and Combinations", "Defending Against Pins and Combinations", "Practical Defensive Sacrifices", "Identifying the Real Threat", "Defensive Psychology", "The Practical Defence Checklist", "Practical Defence Mastery"] },
        { title: "14 Mastering Rook Endings", topics: ["Why Rook Endings Matter", "Bad Piece Placement", "Activity Above Material", "Creating Passed Pawns", "Using Passed Pawns", "Stopping Passed Pawns", "King and Rook Cooperation", "Seventh Rank Domination", "Activating the King", "Cutting Off the King", "Checking Distance", "Pawn Sacrifices in Rook Endings", "Rook Behind the Passed Pawn", "Rook Beside the Passed Pawn", "Rook in Front of the Passed Pawn", "King Safety and Hiding Places", "Liquidating Into Pawn Endings", "Practical Rook Ending Principles", "Rook Ending Mastery"] }
      ]
    }
  ],
  benefits: [
    "Memory", "Concentration", "Problem Solving", "Discipline", "Confidence", "Critical Thinking"
  ]
};
